# Generated by rust2rpm 26
%bcond_without check

%global ver 0.1.0
%global commit 876c73d228c24e7a85e1e39ef7265e1e81d106ca
%global date 20240426.18

Name:           cosmic-clipboard-manager
Version:        %{ver}~git%{date}.%{sub %{commit} 1 7}
Release:        %autorelease
Summary:        Clipboard manager for the COSMIC Desktop Environment

SourceLicense: MIT
License: MIT

URL:            https://github.com/wiiznokes/cosmic-clipboard-manager



BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-comp-%{commit} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
sed 's/\(.*\) (.*#\(.*\))/\1+git\2/' -i cargo-vendor.txt

%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%{_bindir}/cosmic-clipboard-manager
%{_datadir}/applications/io.github.wiiznokes.cosmic-clipboard-manager.desktop
%{_datadir}/share/icons/hicolor/scalable/apps/io.github.wiiznokes.cosmic-clipboard-manager.svg

%changelog
%autochangelog
