# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global ver 0.1.0
%global commit 4d1aef9ec8ca51da115cad9766459d8eb709b29d
%global date 20240426.18

Name:           cosmic-clipboard-manager
Version:        %{ver}~git%{date}.%{sub %{commit} 1 7}
Release:        %autorelease
Summary:        Clipboard manager for wayland

SourceLicense:  MIT
License:        MIT
URL:            https://github.com/wiiznokes/cosmic-clipboard-manager.git

Source:         https://github.com/wiiznokes/cosmic-clipboard-manager/archive/%{commit}.tar.gz

Source:         cosmic-clipboard-manager-0.1.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc DEV.md
%doc README.md
%{_bindir}/cosmic-clipboard-manager
%{_datadir}/applications/io.github.wiiznokes.cosmic-clipboard-manager.desktop
%{_datadir}/share/icons/hicolor/scalable/apps/io.github.wiiznokes.cosmic-clipboard-manager.svg

%changelog
%autochangelog
