name: Flatpak bundle

on:
  workflow_dispatch:
  push:
    branches: flatpak-wf

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build app bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@just
      - uses: Swatinem/rust-cache@v2

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder ostree

      - name: Install flatpak SDKs
        run: just flatpak-install-sdk

      - name: Generate manifest
        run: |
          just flatpak-install-flatpak-builder-tools
          just flatpak-gen-manifest

      - name: Build app
        run: |
          flatpak-builder \
              --verbose \
              --ccache \
              --repo=repo \
              flatpak-out \
              flatpak_schema.json

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle \
            repo \
            clipboard-manager.flatpak \
            io.github.cosmic_utils.cosmic-ext-applet-clipboard-manager \
            testing

      - name: Upload Flatpak bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: clipboard-manager.flatpak
